apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadlgyh2597-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadlgyh2597-tenant-component
    app.kubernetes.io/part-of: loadlgyh2597-tenant-app
  name: loadlgyh2597-tenant-component
  namespace: loadlgyh2597-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadlgyh2597-tenant-component
    weight: null
status: {}
